/**
 * Claves de permisos (espejo de config/constants.js del backend) y
 * etiquetas en español para mostrar el catálogo agrupado por módulo.
 */

export const PERMISSIONS = {
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  ROLES_READ: 'roles.read',
  ROLES_CREATE: 'roles.create',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',
  PERMISSIONS_READ: 'permissions.read',
  COMPANIES_READ: 'companies.read',
  COMPANIES_CREATE: 'companies.create',
  COMPANIES_UPDATE: 'companies.update',
  BRANCHES_READ: 'branches.read',
  BRANCHES_CREATE: 'branches.create',
  BRANCHES_UPDATE: 'branches.update',
  BRANCHES_DELETE: 'branches.delete',
  WAREHOUSES_READ: 'warehouses.read',
  WAREHOUSES_CREATE: 'warehouses.create',
  WAREHOUSES_UPDATE: 'warehouses.update',
  WAREHOUSES_DELETE: 'warehouses.delete',
  CUSTOMERS_READ: 'customers.read',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_UPDATE: 'customers.update',
  CUSTOMERS_DELETE: 'customers.delete',
  SUPPLIERS_READ: 'suppliers.read',
  SUPPLIERS_CREATE: 'suppliers.create',
  SUPPLIERS_UPDATE: 'suppliers.update',
  SUPPLIERS_DELETE: 'suppliers.delete',
  CATEGORIES_READ: 'categories.read',
  CATEGORIES_CREATE: 'categories.create',
  CATEGORIES_UPDATE: 'categories.update',
  CATEGORIES_DELETE: 'categories.delete',
  PRODUCTS_READ: 'products.read',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRODUCTS_DELETE: 'products.delete',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_ENTRY: 'inventory.entry',
  INVENTORY_EXIT: 'inventory.exit',
  INVENTORY_ADJUST: 'inventory.adjust',
  SALES_READ: 'sales.read',
  SALES_CREATE: 'sales.create',
  SALES_UPDATE: 'sales.update',
  SALES_CANCEL: 'sales.cancel',
  PURCHASES_READ: 'purchases.read',
  PURCHASES_CREATE: 'purchases.create',
  PURCHASES_UPDATE: 'purchases.update',
  PURCHASES_CANCEL: 'purchases.cancel',
  DASHBOARD_READ: 'dashboard.read',
  REPORTS_READ: 'reports.read',
  REPORTS_EXPORT: 'reports.export',
  AUDIT_READ: 'audit.read',
  SETTINGS_READ: 'settings.read',
  SETTINGS_UPDATE: 'settings.update',
  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_UPDATE: 'notifications.update',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** Etiqueta de cada permiso (para el editor de roles). */
export const PERMISSION_LABELS: Record<string, string> = {
  'users.read': 'Consultar usuarios',
  'users.create': 'Crear usuarios',
  'users.update': 'Actualizar usuarios',
  'users.delete': 'Desactivar usuarios',
  'roles.read': 'Consultar roles',
  'roles.create': 'Crear roles',
  'roles.update': 'Modificar roles y permisos',
  'roles.delete': 'Eliminar roles no sistema',
  'permissions.read': 'Consultar catálogo de permisos',
  'companies.read': 'Consultar empresas',
  'companies.create': 'Crear empresas',
  'companies.update': 'Actualizar la empresa propia',
  'branches.read': 'Consultar sucursales',
  'branches.create': 'Crear sucursales',
  'branches.update': 'Actualizar sucursales',
  'branches.delete': 'Desactivar sucursales',
  'warehouses.read': 'Consultar almacenes',
  'warehouses.create': 'Crear almacenes',
  'warehouses.update': 'Actualizar almacenes',
  'warehouses.delete': 'Desactivar almacenes',
  'customers.read': 'Consultar clientes',
  'customers.create': 'Crear clientes',
  'customers.update': 'Actualizar clientes',
  'customers.delete': 'Desactivar clientes',
  'suppliers.read': 'Consultar proveedores',
  'suppliers.create': 'Crear proveedores',
  'suppliers.update': 'Actualizar proveedores',
  'suppliers.delete': 'Desactivar proveedores',
  'categories.read': 'Consultar categorías',
  'categories.create': 'Crear categorías',
  'categories.update': 'Actualizar categorías',
  'categories.delete': 'Desactivar categorías',
  'products.read': 'Consultar productos',
  'products.create': 'Crear productos',
  'products.update': 'Actualizar productos',
  'products.delete': 'Desactivar productos',
  'inventory.read': 'Consultar existencias y movimientos',
  'inventory.entry': 'Registrar entradas/devoluciones',
  'inventory.exit': 'Registrar salidas',
  'inventory.adjust': 'Ajustar existencias',
  'sales.read': 'Consultar ventas',
  'sales.create': 'Crear y editar borradores de venta',
  'sales.update': 'Confirmar/completar ventas',
  'sales.cancel': 'Cancelar ventas',
  'purchases.read': 'Consultar compras',
  'purchases.create': 'Crear y editar borradores de compra',
  'purchases.update': 'Confirmar/recibir compras',
  'purchases.cancel': 'Cancelar compras',
  'dashboard.read': 'Ver panel de indicadores',
  'reports.read': 'Generar reportes',
  'reports.export': 'Exportar reportes (CSV)',
  'audit.read': 'Consultar auditoría (solo lectura)',
  'settings.read': 'Ver configuración de la empresa',
  'settings.update': 'Modificar configuración de la empresa',
  'notifications.read': 'Ver notificaciones',
  'notifications.update': 'Gestionar notificaciones',
};

/** Nombre legible de cada módulo de permisos. */
export const MODULE_LABELS: Record<string, string> = {
  users: 'Usuarios',
  roles: 'Roles',
  permissions: 'Permisos',
  companies: 'Empresas',
  branches: 'Sucursales',
  warehouses: 'Almacenes',
  customers: 'Clientes',
  suppliers: 'Proveedores',
  categories: 'Categorías',
  products: 'Productos',
  inventory: 'Inventario',
  sales: 'Ventas',
  purchases: 'Compras',
  dashboard: 'Panel',
  reports: 'Informes',
  audit: 'Auditoría',
  settings: 'Ajustes',
  notifications: 'Notificaciones',
};

/** Orden de los módulos en el editor de roles. */
export const MODULE_ORDER = [
  'users',
  'roles',
  'permissions',
  'companies',
  'branches',
  'warehouses',
  'customers',
  'suppliers',
  'categories',
  'products',
  'inventory',
  'sales',
  'purchases',
  'dashboard',
  'reports',
  'audit',
  'settings',
  'notifications',
];
